# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Actions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My Actions
  pod “CloudBoost”  

  target 'My ActionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My ActionsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
